### ISSUE TITLE
Glorified global var

### ISSUE THREAD

**Issue by mfrost66** [PolymerElements/iron-meta#16]
How is this any different than a global variable?  Except that your "monostate" is 300 lines long. What happens when your element and mine both use the same key? Foobar indeed.

Semantically the same as:
```javascript
window['iron-meta'][key] = value
```

**Comment by ebidel** [comment]
Irin-meta has an API surface and can be imported and depended on by other elements. It has useful functionality other than being a shared "global". Or elements use it because it's useful as a shared db. You're free I use whatever you want. 

https://github.com/PolymerElements/iron-meta has more info in the readme. 

Closing as this is not an issue.

**Comment by mfrost66** [comment]
The issue is that polymer doesn't fundamentally solve the problem of finding dynamic elements.  That the polymer component team has resorted to this to register and find dynamic elements underscores the need.  

BTW ``window.Polymer['iron-meta'][myKey]``` also has an API surface, can be depended on to exist, and is useful as a shared db - and happens to also be functionally what you're doing.  Oh, and it already exists, doesn't need tested, maintained or documented.
